name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this according to your repository's default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build  # Adjust this command according to your Eleventy build command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./_site  # Adjust this according to your Eleventy output directory
          publish_branch: gh-pages